# Spring Boot Application Configuration
spring.application.name=CS320 Service Management API

# Server Configuration
server.port=8080

# JSON Configuration
spring.jackson.serialization.indent_output=true

# Logging Configuration
logging.level.root=INFO
logging.level.api=INFO
